version: '3'

services:
  postgres:
    container_name: pandas_etl_postgres
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: orders
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    restart: unless-stopped

  mysql:
    container_name: pandas_etl_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: orders
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    restart: unless-stopped
